from machine.AbruptVaryingMachine import AbruptVaryingMachine
from machine.FastVaryingMachine import FastVaryingMachine
from machine.SlowVaryingMachine import SlowVaryingMachine
from machine.StaticMachine import StaticMachine
from machine.TestMachine import TestMachine
